### ISSUE TITLE
I have a question with FileNotFoundError: [Errno 2] No such file or directory: './vgg19.pth'

### ISSUE THREAD

**Issue by fly125** [liuzhi19121999/AnimeGANv3Pytorch#2]
I can't get the file.
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\AnimeGANv2Pytorch\diff_fly\pix2pix_anime\AnimeGANv3Pytorch\train.py", line 1, in <module>
    from AnimeGAN import Trainer
  File "D:\BaiduNetdiskDownload\AnimeGANv2Pytorch\diff_fly\pix2pix_anime\AnimeGANv3Pytorch\AnimeGAN.py", line 6, in <module>
    from ops import con_loss_fn, style_loss_decentralization_3, region_smoothing_loss, \
  File "D:\BaiduNetdiskDownload\AnimeGANv2Pytorch\diff_fly\pix2pix_anime\AnimeGANv3Pytorch\ops.py", line 4, in <module>
    from vgg19 import VGG19Multi, VGG19Single
  File "D:\BaiduNetdiskDownload\AnimeGANv2Pytorch\diff_fly\pix2pix_anime\AnimeGANv3Pytorch\vgg19.py", line 28, in <module>
    vgg19_data = torch.load("./vgg19.pth")
  File "D:\BaiduNetdiskDownload\AnimeGANv2Pytorch\animeganv2_pytorch_venv\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\BaiduNetdiskDownload\AnimeGANv2Pytorch\animeganv2_pytorch_venv\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\BaiduNetdiskDownload\AnimeGANv2Pytorch\animeganv2_pytorch_venv\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './vgg19.pth'

**Comment by liuzhi19121999** [comment]
VGG19.pth is the pytorch model data in root directory of project. It can be downloaded in [Essential Resource](https://github.com/liuzhi19121999/AnimeGANv3Pytorch/releases/tag/Resources)
